config/routes.rb
Rails.application.routes.draw do
  resources :customers

  root 'customers#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base

	geocoded_by :address
	after_validation :geocode

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
require 'open_weather'

class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
    getMarkers @customers
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    getMarkers @customer
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:latitude, :longitude, :name, :address, :more_info, :age)
    end

    def getMarkers customers
    @hash = Gmaps4rails.build_markers(customers) do |customer, marker|
      marker.lat customer.latitude
      marker.lng customer.longitude
      temp = getTemp customer.latitude, customer.longitude
      marker.infowindow "<p style='font-family: Verdana; font-size: 12px; color: blue;'>Customer: #{customer.name}<br> Age: #{customer.age}<br> Inf- #{customer.more_info}<br>Temp: #{temp} Celcius</p>"
    end
  end

  def getTemp lat, long
    options = { units: "metric", APPID: "c8ede9021d3ebaacf3f144b672b393b1"}
    response = OpenWeather::Current.geocode(lat, long, options)
    response["main"]["temp"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @customer.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h4>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :more_info, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :more_info, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :age, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :age, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="page-header">
  <%= link_to customers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @customer, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing customer</h1>
</div>

<%= render 'form' %>

app/views/customers/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyD0odVNjELVAzOCFiywP7t_aEG_VPusGUo"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<div class="page-header">
  <%= link_to new_customer_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Customer
  <% end %>
  <h1>Listing customers</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Address</th>
            <th>More info</th>
            <th>Age</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @customers) do |customer| %>
            <td><%= customer.name %></td>
            <td><%= customer.address %></td>
            <td><%= customer.more_info %></td>
            <td><%= customer.age %></td>
            <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

<div style='width: 100%;'>
  <div id="map" style='width: 100%; height: 400px;'></div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/customers/new.html.erb
<div class="page-header">
  <%= link_to customers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New customer</h1>
</div>

<%= render 'form' %>

app/views/customers/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyD0odVNjELVAzOCFiywP7t_aEG_VPusGUo"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


<div class="page-header">
  <%= link_to customers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_customer_path(@customer), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show customer</h1>
</div>

<dl class="dl-horizontal">
  <dt>Latitude:</dt>
  <dd><%= @customer.latitude %></dd>

  <dt>Longitude:</dt>
  <dd><%= @customer.longitude %></dd>

  <dt>Name:</dt>
  <dd><%= @customer.name %></dd>

  <dt>Address:</dt>
  <dd><%= @customer.address %></dd>

  <dt>More info:</dt>
  <dd><%= @customer.more_info %></dd>

  <dt>Age:</dt>
  <dd><%= @customer.age %></dd>

</dl>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Just a simple app using bootstrap/Google Maps/Weather</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Customer map/Weather", "#", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>